baseURL = "https://phyqh.github.io/"
copyright = "Â© HE Qihao"
languageCode = "en-us"
theme = "hugo-ink"
title = "HE Qihao"
# Code Highlight
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsstyle = "vs"
paginate = 10 # articles per page

[params]
  avatar = "images/myself_rec.jpg"
  mode = "light"
  featherIconsCDN = true
  subtitle = "Graphics and Games!"
  excludedTypes = ["page", "pages"]
  customcss = "css/custom.css"
  favicon = "images/icons/genshin-impact.png"

[[params.social]]
icon = "github"
name = "GitHub"
url = "https://github.com/phyqh"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
